/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dbrwmwhnssjtvhbzdmpx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicndtd2huc3NqdHZoYnpkbXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMjY2MjEsImV4cCI6MjA4ODYwMjYyMX0.TGMMQ9vLQteDnDP9YXq-E-FPKms3bvRb37mPRDIVpsY"